<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUloxb9x\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUloxb9x/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUloxb9x.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUloxb9x\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUloxb9x\appProdProjectContainer([
    'container.build_hash' => 'Uloxb9x',
    'container.build_id' => '8746a544',
    'container.build_time' => 1591953254,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUloxb9x');
