<?php

namespace Proxies\__CG__\PrestaShopBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Attribute extends \PrestaShopBundle\Entity\Attribute implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'PrestaShopBundle\\Entity\\Attribute' . "\0" . 'id', '' . "\0" . 'PrestaShopBundle\\Entity\\Attribute' . "\0" . 'attributeGroup', '' . "\0" . 'PrestaShopBundle\\Entity\\Attribute' . "\0" . 'color', '' . "\0" . 'PrestaShopBundle\\Entity\\Attribute' . "\0" . 'position', '' . "\0" . 'PrestaShopBundle\\Entity\\Attribute' . "\0" . 'shops', '' . "\0" . 'PrestaShopBundle\\Entity\\Attribute' . "\0" . 'attributeLangs');
        }

        return array('__isInitialized__', '' . "\0" . 'PrestaShopBundle\\Entity\\Attribute' . "\0" . 'id', '' . "\0" . 'PrestaShopBundle\\Entity\\Attribute' . "\0" . 'attributeGroup', '' . "\0" . 'PrestaShopBundle\\Entity\\Attribute' . "\0" . 'color', '' . "\0" . 'PrestaShopBundle\\Entity\\Attribute' . "\0" . 'position', '' . "\0" . 'PrestaShopBundle\\Entity\\Attribute' . "\0" . 'shops', '' . "\0" . 'PrestaShopBundle\\Entity\\Attribute' . "\0" . 'attributeLangs');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Attribute $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setColor($color)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColor', array($color));

        return parent::setColor($color);
    }

    /**
     * {@inheritDoc}
     */
    public function getColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColor', array());

        return parent::getColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosition($position)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosition', array($position));

        return parent::setPosition($position);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosition', array());

        return parent::getPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttributeGroup(\PrestaShopBundle\Entity\AttributeGroup $attributeGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttributeGroup', array($attributeGroup));

        return parent::setAttributeGroup($attributeGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributeGroup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeGroup', array());

        return parent::getAttributeGroup();
    }

    /**
     * {@inheritDoc}
     */
    public function addShop(\PrestaShopBundle\Entity\Shop $shop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addShop', array($shop));

        return parent::addShop($shop);
    }

    /**
     * {@inheritDoc}
     */
    public function removeShop(\PrestaShopBundle\Entity\Shop $shop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeShop', array($shop));

        return parent::removeShop($shop);
    }

    /**
     * {@inheritDoc}
     */
    public function getShops()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShops', array());

        return parent::getShops();
    }

    /**
     * {@inheritDoc}
     */
    public function addAttributeLang(\PrestaShopBundle\Entity\AttributeLang $attributeLang)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAttributeLang', array($attributeLang));

        return parent::addAttributeLang($attributeLang);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAttributeLang(\PrestaShopBundle\Entity\AttributeLang $attributeLang)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAttributeLang', array($attributeLang));

        return parent::removeAttributeLang($attributeLang);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributeLangs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeLangs', array());

        return parent::getAttributeLangs();
    }

}
